name: vertex
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.5
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # <-- Deve estar aqui, nÃ£o dentro de flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo-inverse.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"